name: Build and Deploy Hugo Site to User Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for the GitHub Actions token (mantenha 'write' para que a action possa escrever)
permissions:
  contents: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    # INJEÇÃO DO SEGREDO COMO VARIÁVEL DE AMBIENTE (Crucial para o fix)
    env:
      GITHUB_TOKEN: ${{ secrets.HUGO_DEPLOY }} # Certifique-se que 'HUGO_DEPLOY' é o nome exato do seu Segredo!
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup and Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true 
      
      - name: Build Hugo Site
        run: hugo --minify 
        
      # Deploy to the target repository using the injected environment variable
      - name: Deploy to GitHub Pages (User Repo)
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token injetado via 'env:'. REMOVA o 'github_token' daqui para usar a variável de ambiente.
          
          # TARGET REPOSITORY: Mantenha esta linha correta.
          external_repository: meminject/meminject.github.io 
          
          publish_branch: main 
          publish_dir: ./public 
          force_orphan: true
